CONFIG_GPIO=y
CONFIG_I2C=y

# We are using nrfx SAADC directly, not Zephyr's ADC driver.
CONFIG_ADC=n
CONFIG_NRFX_SAADC=y

CONFIG_PRINTK=y
CONFIG_THREAD_NAME=y
CONFIG_MAIN_THREAD_PRIORITY=5

CONFIG_DRUM_DIAGNOSTICS=y
CONFIG_DRUM_ADC_TIMING_DIAGNOSTICS=y
CONFIG_DRUM_FAKE_TRIGGER_TEST=n
CONFIG_DRUM_SAADC_STREAM=y

CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
